"""init schema 8 tables

Revision ID: b630246c4cd1
Revises: 
Create Date: 2026-07-16 10:41:01.513185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b630246c4cd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 启用 pg_trgm 扩展（标题模糊匹配）
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('trend_analysis', sa.Text(), nullable=True),
    sa.Column('risk_alerts', sa.Text(), nullable=True),
    sa.Column('action_suggestions', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_trace_id'), 'operation_logs', ['trace_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sorftime_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('monthly_sales', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('listing_monopoly', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brand_monopoly', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seller_monopoly', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('new_product_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seller_count', sa.Integer(), nullable=True),
    sa.Column('amazon_self_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('matched_1688_id', sa.String(length=64), nullable=True),
    sa.Column('matched_1688_title', sa.String(length=500), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('risk_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('comprehensive_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_comprehensive_score'), 'products', ['comprehensive_score'], unique=False)
    op.create_index(op.f('ix_products_data_date'), 'products', ['data_date'], unique=False)
    op.create_index(op.f('ix_products_match_status'), 'products', ['match_status'], unique=False)
    op.create_index(op.f('ix_products_sorftime_id'), 'products', ['sorftime_id'], unique=True)
    op.create_table('risk_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_tag', sa.String(length=50), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_1688', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_1688_previous', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_change_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_unit', sa.String(length=20), nullable=False),
    sa.Column('price_platform', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_platform_previous', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_product_id'), 'price_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_snapshot_date'), 'price_snapshots', ['snapshot_date'], unique=False)
    op.create_table('product_metrics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('monthly_sales', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'metric_date', name='uq_metrics_product_date')
    )
    op.create_index(op.f('ix_product_metrics_daily_product_id'), 'product_metrics_daily', ['product_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expected_daily_orders', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_rank_position'), 'recommendations', ['rank_position'], unique=False)
    op.create_index(op.f('ix_recommendations_week_start'), 'recommendations', ['week_start'], unique=False)
    # ### commands auto generated by Alembic - please adjust! ###

    # 标题模糊匹配索引（pg_trgm，对应数据库设计 products 表）
    op.execute(
        "CREATE INDEX idx_products_title_trgm ON products USING gin (title gin_trgm_ops)"
    )

    # 预置风险规则（对应数据库设计 4.1 表6）
    risk_rules_table = sa.table(
        "risk_rules",
        sa.column("rule_name", sa.String),
        sa.column("trigger_conditions", sa.dialects.postgresql.JSONB),
        sa.column("risk_level", sa.String),
        sa.column("risk_tag", sa.String),
        sa.column("alert_message", sa.Text),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(risk_rules_table, [
        {
            "rule_name": "墨水-易燃液体",
            "trigger_conditions": {"category": "ink", "type": "oil_based"},
            "risk_level": "danger",
            "risk_tag": "易燃液体",
            "alert_message": "⛔ 属3类易燃液体，需MSDS+非危鉴定，空运受限",
            "is_active": True,
        },
        {
            "rule_name": "相纸-易损",
            "trigger_conditions": {"category": "photo_paper"},
            "risk_level": "warning",
            "risk_tag": "易损易潮",
            "alert_message": "⚠️ 需三重包装+干燥剂，运输破损率高",
            "is_active": True,
        },
    ])

    # 预置系统配置（对应数据库设计 4.1 表7）
    system_configs_table = sa.table(
        "system_configs",
        sa.column("config_key", sa.String),
        sa.column("config_value", sa.dialects.postgresql.JSONB),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(system_configs_table, [
        {
            "config_key": "ai.model_priority",
            "config_value": {"primary": "glm-5.2", "backup": ["glm-5.1", "deepseek", "minimax"]},
            "description": "AI模型优先级",
        },
        {
            "config_key": "algorithm.thresholds",
            "config_value": {"monthly_sales_min": 5000, "monthly_sales_max": 150000, "listing_monopoly": 30},
            "description": "选品阈值",
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # 清理预置数据与扩展索引
    op.execute("DELETE FROM system_configs WHERE config_key IN ('ai.model_priority','algorithm.thresholds')")
    op.execute("DELETE FROM risk_rules WHERE rule_name IN ('墨水-易燃液体','相纸-易损')")
    op.execute("DROP INDEX IF EXISTS idx_products_title_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_week_start'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_rank_position'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_product_metrics_daily_product_id'), table_name='product_metrics_daily')
    op.drop_table('product_metrics_daily')
    op.drop_index(op.f('ix_price_snapshots_snapshot_date'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_product_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('system_configs')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_products_sorftime_id'), table_name='products')
    op.drop_index(op.f('ix_products_match_status'), table_name='products')
    op.drop_index(op.f('ix_products_data_date'), table_name='products')
    op.drop_index(op.f('ix_products_comprehensive_score'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_operation_logs_trace_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('daily_reports')
    # ### commands auto generated by Alembic - please adjust! ###

    # 标题模糊匹配索引（pg_trgm，对应数据库设计 products 表）
    op.execute(
        "CREATE INDEX idx_products_title_trgm ON products USING gin (title gin_trgm_ops)"
    )

    # 预置风险规则（对应数据库设计 4.1 表6）
    risk_rules_table = sa.table(
        "risk_rules",
        sa.column("rule_name", sa.String),
        sa.column("trigger_conditions", sa.dialects.postgresql.JSONB),
        sa.column("risk_level", sa.String),
        sa.column("risk_tag", sa.String),
        sa.column("alert_message", sa.Text),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(risk_rules_table, [
        {
            "rule_name": "墨水-易燃液体",
            "trigger_conditions": {"category": "ink", "type": "oil_based"},
            "risk_level": "danger",
            "risk_tag": "易燃液体",
            "alert_message": "⛔ 属3类易燃液体，需MSDS+非危鉴定，空运受限",
            "is_active": True,
        },
        {
            "rule_name": "相纸-易损",
            "trigger_conditions": {"category": "photo_paper"},
            "risk_level": "warning",
            "risk_tag": "易损易潮",
            "alert_message": "⚠️ 需三重包装+干燥剂，运输破损率高",
            "is_active": True,
        },
    ])

    # 预置系统配置（对应数据库设计 4.1 表7）
    system_configs_table = sa.table(
        "system_configs",
        sa.column("config_key", sa.String),
        sa.column("config_value", sa.dialects.postgresql.JSONB),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(system_configs_table, [
        {
            "config_key": "ai.model_priority",
            "config_value": {"primary": "glm-5.2", "backup": ["glm-5.1", "deepseek", "minimax"]},
            "description": "AI模型优先级",
        },
        {
            "config_key": "algorithm.thresholds",
            "config_value": {"monthly_sales_min": 5000, "monthly_sales_max": 150000, "listing_monopoly": 30},
            "description": "选品阈值",
        },
    ])
    # ### end Alembic commands ###
